Fix: problem detected by brew audit [complete]
All problems are fixed.
Only 'test' block is needed to be passed through '--strict' audit
```
cj-bc/onefetch/onefetch:
  * C: 4: col 3: `desc` (line 4) should be put before `homepage` (line
2)
Error: 1 problem in 1 formula detected
```